version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/simulations"
    schedule:
      interval: "weekly"
    assignees:
      - "mnemonice"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "mnemonice"
