ls:
  simulations/*:
    .py: snake_case
  contracts/src/*:
    .sol: PascalCase
  contracts/test/*:
    .sol: PascalCase
  docs/*:
    .md: lowercase
    .png: snake_case
ignore:
  - .git
  - .github
  - node_modules
  - __pycache__
  - contracts/lib
