sonar.projectKey=mnemonice_credon-core
sonar.organization=mnemonice

# Core analysis directories
sonar.sources=simulations
sonar.python.version=3.11

# Exclude test files from duplication and general metrics, but include them for test analysis
sonar.exclusions=simulations/test_*.py
sonar.tests=simulations
sonar.test.inclusions=simulations/test_*.py

# Provide path to the coverage reports to prevent failure if it does not find any tests
sonar.python.coverage.reportPaths=coverage.xml

sonar.qualitygate.wait=false
