name: Sync Docs to Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync /docs to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v5
        with:
          path: docs/
        env:
          WIKI_DIR: docs/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
